/*
 * This file is part of ProGearSDK.
 * Copyright (c) 2024-2025 ProGearSDK contributors
 * SPDX-License-Identifier: MIT
 */

/**
 * @file audio.h
 * @brief Sound effects and music playback.
 *
 * Simple audio playback using ADPCM samples defined in assets.yaml.
 *
 * @example
 * // Play a sound effect
 * AudioPlaySfx(SFX_JUMP);
 *
 * // Play background music
 * AudioPlayMusic(MUSIC_STAGE1);
 *
 * // Adjust volume
 * AudioSetVolume(12);
 */

#ifndef AUDIO_H
#define AUDIO_H

#include <types.h>

/* Forward declaration - Actor is defined in actor.h */
typedef s8 Actor;

/** @defgroup audioasset Audio Asset Types
 *  @brief Asset definitions generated by progear_assets.py.
 *  @{
 */

/**
 * Sound effect asset definition.
 * Generated by progear_assets.py from assets.yaml sfx entries.
 */
typedef struct {
    const char *name; /**< SFX name */
    u8 index;         /**< ADPCM-A channel index */
} SfxAsset;

/**
 * Music asset definition.
 * Generated by progear_assets.py from assets.yaml music entries.
 */
typedef struct {
    const char *name; /**< Music name */
    u8 index;         /**< ADPCM-B channel index */
} MusicAsset;

/** @} */

/**
 * @defgroup audio Audio
 * @brief Sound effects and music.
 * @{
 */

/** Maximum number of sound effects */
#define AUDIO_MAX_SFX 32

/** Maximum number of music tracks */
#define AUDIO_MAX_MUSIC 32

/** Maximum volume level */
#define AUDIO_MAX_VOLUME 15

/** Number of SFX channels */
#define AUDIO_CHANNELS 6

/**
 * Play a sound effect.
 *
 * @param sfx_index SFX index (0-31, as defined in assets.yaml)
 */
void AudioPlaySfx(u8 sfx_index);

/**
 * Play a sound effect at an actor's position.
 * Automatically calculates stereo panning based on screen position.
 *
 * @param actor Actor to use for position
 * @param sfx_index SFX index
 */
void AudioPlaySfxAt(Actor actor, u8 sfx_index);

/**
 * Stop a specific SFX channel.
 *
 * @param channel Channel index (0-5)
 */
void AudioStopSfx(u8 channel);

/**
 * Stop all sound effects.
 */
void AudioStopAllSfx(void);

/**
 * Play music (loops indefinitely).
 *
 * @param music_index Music index (0-31, as defined in assets.yaml)
 */
void AudioPlayMusic(u8 music_index);

/**
 * Stop music playback.
 */
void AudioStopMusic(void);

/**
 * Pause music playback.
 * Use AudioResumeMusic() to continue.
 */
void AudioPauseMusic(void);

/**
 * Resume paused music.
 */
void AudioResumeMusic(void);

/**
 * Check if music is currently playing.
 *
 * @return Non-zero if music is playing
 */
u8 AudioMusicPlaying(void);

/**
 * Check if music is paused.
 *
 * @return Non-zero if music is paused
 */
u8 AudioMusicPaused(void);

/**
 * Get the currently playing music index.
 *
 * @return Music index, or 0xFF if none playing
 */
u8 AudioGetMusic(void);

/**
 * Set master volume.
 *
 * @param volume Volume level (0-15, where 15 is loudest)
 */
void AudioSetVolume(u8 volume);

/**
 * Get current volume level.
 *
 * @return Current volume (0-15)
 */
u8 AudioGetVolume(void);

/**
 * Stop all audio (both SFX and music).
 */
void AudioStopAll(void);

/*
 * Internal functions - called by engine.
 */
void AudioInit(void);

/** @} */

#endif /* AUDIO_H */
