/**
 * @file progearsdk.h
 * @brief Convenience header that includes the entire ProGearSDK.
 *
 * Include this single header to access all SDK functionality:
 * @code
 * #include <progearsdk.h>
 * @endcode
 *
 * Note: This does not include ngres_generated_assets.h, which is
 * application-specific and generated by the asset pipeline.
 */

#ifndef _PROGEARSDK_H_
#define _PROGEARSDK_H_

/* Foundational types and hardware definitions */
#include <types.h>
#include <neogeo.h>
#include <ngmath.h>

/* Color and palette management */
#include <color.h>
#include <palette.h>

/* Memory allocation */
#include <arena.h>

/* Input handling */
#include <input.h>

/* Fix layer (text/HUD) */
#include <fix.h>

/* Visual assets and actors */
#include <visual.h>
#include <actor.h>
#include <scene.h>

/* Camera system */
#include <camera.h>

/* World rendering */
#include <parallax.h>
#include <tilemap.h>

/* Physics */
#include <physics.h>

/* UI and animation */
#include <spring.h>
#include <ui.h>

/* Audio */
#include <audio.h>

/* Engine lifecycle */
#include <engine.h>

#endif /* _PROGEARSDK_H_ */
