/**
 * @file progearsdk.h
 * @brief Convenience header that includes the entire ProGearSDK.
 *
 * Include this single header to access all SDK functionality:
 * @code
 * #include <progearsdk.h>
 * @endcode
 *
 * Note: This does not include progear_assets.h, which is
 * application-specific and generated by the asset pipeline.
 */

#ifndef _PROGEARSDK_H_
#define _PROGEARSDK_H_

/* Hardware Abstraction Layer (provides types, hardware, math, color,
 * palette, sprite, fix, input, audio, arena) */
#include <neogeo_hal.h>

/* Visual assets and graphics */
#include <visual.h>
#include <graphic.h>
#include <actor.h>
#include <scene.h>
#include <terrain.h>

/* Camera system */
#include <camera.h>

/* Backdrops (parallax background layers) */
#include <backdrop.h>

/* Physics */
#include <physics.h>

/* Lighting effects */
#include <lighting.h>

/* UI and animation */
#include <spring.h>
#include <ui.h>

/* Engine lifecycle */
#include <engine.h>

#endif /* _PROGEARSDK_H_ */
