/*
 * This file is part of ProGearSDK.
 * Copyright (c) 2024-2025 ProGearSDK contributors
 * SPDX-License-Identifier: MIT
 */

/**
 * @file terrain.h
 * @brief Tile-based terrain rendering with collision support.
 *
 * Terrain renders large scrolling worlds efficiently by only displaying
 * visible tiles within the camera viewport. Tiles outside the view are
 * not rendered, allowing worlds much larger than sprite limits.
 *
 * Key features:
 * - Efficient viewport windowing (renders only visible tiles)
 * - Lightweight tile collision queries (no physics bodies per tile)
 * - Per-tile palette support via tileset palette regions
 *
 * @section terrainworkflow Workflow
 * 1. Create tileset in Tiled editor from 16x16 tile PNG
 * 2. Design levels using Tiled's visual editor
 * 3. Set tile properties (solid, platform, hazard) in Tiled
 * 4. Export as TMX, reference in assets.yaml under `tilemaps:`
 * 5. progear_assets.py generates TerrainAsset
 */

#ifndef TERRAIN_H
#define TERRAIN_H

#include <types.h>
#include <ngmath.h>
#include <hw/lspc.h>

/** @defgroup terrainconst Constants
 *  @{
 *  TILE_SIZE is defined in hw/lspc.h as the single source of truth.
 */

#define TERRAIN_MAX     4    /**< Maximum active terrains */
#define TERRAIN_INVALID (-1) /**< Invalid handle sentinel */

/** Maximum columns renderable (screen width / 16 + 2 for scroll buffer) */
#define TERRAIN_MAX_COLS 22

/** Maximum rows renderable (limited by 512px hardware constraint) */
#define TERRAIN_MAX_ROWS 32

/** @} */

/** @defgroup tilecoll Tile Collision Flags
 *  @{
 */

#define TILE_SOLID    0x01 /**< Blocks movement (walls/floors) */
#define TILE_PLATFORM 0x02 /**< One-way platform (solid from above) */
#define TILE_SLOPE_L  0x04 /**< Left-to-right slope */
#define TILE_SLOPE_R  0x08 /**< Right-to-left slope */
#define TILE_HAZARD   0x10 /**< Damages player on contact */
#define TILE_TRIGGER  0x20 /**< Triggers callback on contact */
#define TILE_LADDER   0x40 /**< Climbable tile */

/** @} */

/** @defgroup tilecollres Collision Resolution Flags
 *  @{
 */

#define COLL_NONE   0x00 /**< No collision */
#define COLL_LEFT   0x01 /**< Hit tile on left */
#define COLL_RIGHT  0x02 /**< Hit tile on right */
#define COLL_TOP    0x04 /**< Hit tile above */
#define COLL_BOTTOM 0x08 /**< Hit tile below (landed) */

/** @} */

/** @defgroup terrainhandle Handle Type
 *  @{
 */

/** Terrain handle type */
typedef s8 TerrainHandle;

/** @} */

/** @defgroup terraindata Terrain Data Structures
 *  @{
 */

/**
 * Terrain asset definition.
 * Generated by progear_assets.py from TMX files.
 */
typedef struct TerrainAsset {
    const char *name;          /**< Asset name */
    u16 width_tiles;           /**< Map width in tiles */
    u16 height_tiles;          /**< Map height in tiles */
    u16 base_tile;             /**< First tile in C-ROM for tileset */
    const u8 *tile_data;       /**< Tile indices (row-major, 1 byte per tile) */
    const u8 *collision_data;  /**< Collision flags (row-major, NULL = no collision) */
    const u8 *tile_to_palette; /**< Palette lookup table (256 entries) */
    u8 default_palette;        /**< Fallback palette for unmapped tiles */
} TerrainAsset;

/** @} */

/** @defgroup terrainlife Lifecycle Functions
 *  @{
 */

/**
 * Create a terrain from an asset.
 * @param asset Terrain asset (generated by progear_assets.py)
 * @return Handle or TERRAIN_INVALID if no slots available
 */
TerrainHandle TerrainCreate(const TerrainAsset *asset);

/**
 * Add terrain to scene.
 * @param terrain Terrain handle
 * @param world_x World X offset (fixed-point)
 * @param world_y World Y offset (fixed-point)
 * @param z Z-index for render order
 */
void TerrainAddToScene(TerrainHandle terrain, fixed world_x, fixed world_y, u8 z);

/**
 * Remove terrain from scene (can re-add later).
 * @param terrain Terrain handle
 */
void TerrainRemoveFromScene(TerrainHandle terrain);

/**
 * Destroy terrain and free resources.
 * @param terrain Terrain handle
 */
void TerrainDestroy(TerrainHandle terrain);

/** @} */

/** @defgroup terrainprop Properties
 *  @{
 */

/**
 * Set terrain world position.
 * @param terrain Terrain handle
 * @param world_x World X offset (fixed-point)
 * @param world_y World Y offset (fixed-point)
 */
void TerrainSetPos(TerrainHandle terrain, fixed world_x, fixed world_y);

/**
 * Set terrain Z-index.
 * @param terrain Terrain handle
 * @param z Z-index
 */
void TerrainSetZ(TerrainHandle terrain, u8 z);

/**
 * Set terrain visibility.
 * @param terrain Terrain handle
 * @param visible 1 to show, 0 to hide
 */
void TerrainSetVisible(TerrainHandle terrain, u8 visible);

/**
 * Get terrain world dimensions.
 * @param terrain Terrain handle
 * @param width_out Output: width in pixels (can be NULL)
 * @param height_out Output: height in pixels (can be NULL)
 */
void TerrainGetDimensions(TerrainHandle terrain, u16 *width_out, u16 *height_out);

/** @} */

/** @defgroup terraincoll Collision Functions
 *  @{
 */

/**
 * Query tile collision at world position.
 * @param terrain Terrain handle
 * @param world_x World X position (fixed-point)
 * @param world_y World Y position (fixed-point)
 * @return Collision flags, or 0 if out of bounds
 */
u8 TerrainGetCollision(TerrainHandle terrain, fixed world_x, fixed world_y);

/**
 * Query tile index at grid position.
 * @param terrain Terrain handle
 * @param tile_x Tile X coordinate
 * @param tile_y Tile Y coordinate
 * @return Tile index, or 0 if out of bounds
 */
u8 TerrainGetTileAt(TerrainHandle terrain, u16 tile_x, u16 tile_y);

/**
 * Test AABB collision against terrain.
 * @param terrain Terrain handle
 * @param x Center X (fixed-point)
 * @param y Center Y (fixed-point)
 * @param half_w Half-width (fixed-point)
 * @param half_h Half-height (fixed-point)
 * @param flags_out Output: OR'd collision flags (can be NULL)
 * @return 1 if any solid collision, 0 if no collision
 */
u8 TerrainTestAABB(TerrainHandle terrain, fixed x, fixed y, fixed half_w, fixed half_h,
                   u8 *flags_out);

/**
 * Resolve AABB collision against terrain.
 * @param terrain Terrain handle
 * @param x Center X (fixed-point, modified on collision)
 * @param y Center Y (fixed-point, modified on collision)
 * @param half_w Half-width (fixed-point)
 * @param half_h Half-height (fixed-point)
 * @param vel_x Velocity X (fixed-point, zeroed on collision)
 * @param vel_y Velocity Y (fixed-point, zeroed on collision)
 * @return Collision direction bitmask (COLL_LEFT|RIGHT|TOP|BOTTOM)
 */
u8 TerrainResolveAABB(TerrainHandle terrain, fixed *x, fixed *y, fixed half_w, fixed half_h,
                      fixed *vel_x, fixed *vel_y);

/** @} */

/** @defgroup terrainmod Tile Modification
 *  @{
 */

/**
 * Set tile at grid position.
 * @param terrain Terrain handle
 * @param tile_x Tile X coordinate
 * @param tile_y Tile Y coordinate
 * @param tile_index New tile index
 */
void TerrainSetTile(TerrainHandle terrain, u16 tile_x, u16 tile_y, u8 tile_index);

/**
 * Set collision at grid position.
 * @param terrain Terrain handle
 * @param tile_x Tile X coordinate
 * @param tile_y Tile Y coordinate
 * @param collision New collision flags
 */
void TerrainSetCollision(TerrainHandle terrain, u16 tile_x, u16 tile_y, u8 collision);

/** @} */

/*
 * Internal functions - used by other SDK modules.
 */
void _TerrainSystemInit(void);
void _TerrainDraw(TerrainHandle handle, u16 first_sprite);
u8 _TerrainGetSpriteCount(TerrainHandle handle);

#endif /* TERRAIN_H */
