/*
 * This file is part of ProGearSDK.
 * Copyright (c) 2024-2025 ProGearSDK contributors
 * SPDX-License-Identifier: MIT
 */

/**
 * @file tilemap.h
 * @brief Tile-based world rendering with collision support.
 *
 * NGTilemap renders large scrolling worlds efficiently by only displaying
 * visible tiles within the camera viewport. Tiles outside the view are
 * not rendered, allowing worlds much larger than sprite limits.
 *
 * Key features:
 * - Efficient viewport windowing (renders only visible tiles)
 * - Lightweight tile collision queries (no physics bodies per tile)
 * - Per-tile palette support via tileset palette regions
 * - Integrates with camera, scene, and physics systems
 *
 * @section tilemapworkflow Workflow
 * 1. Create tileset in Tiled editor from 16x16 tile PNG
 * 2. Design levels using Tiled's visual editor
 * 3. Set tile properties (solid, platform, hazard) in Tiled
 * 4. Export as TMX, reference in assets.yaml
 * 5. progear_assets.py generates NGTilemapAsset
 *
 * @section tilemapusage Usage
 * 1. Create tilemap with NGTilemapCreate()
 * 2. Add to scene with NGTilemapAddToScene()
 * 3. Use NGTilemapTestAABB() for collision detection
 * 4. Use NGTilemapResolveAABB() for collision response
 */

#ifndef _TILEMAP_H_
#define _TILEMAP_H_

#include <types.h>
#include <ngmath.h>

/** @defgroup tilemapconst Constants
 *  @{
 */

#define NG_TILEMAP_MAX     4    /**< Maximum active tilemaps */
#define NG_TILEMAP_INVALID (-1) /**< Invalid handle sentinel */
#define NG_TILE_SIZE       16   /**< Tile size in pixels */

/** Maximum columns renderable (screen width / 16 + 2 for scroll buffer) */
#define NG_TILEMAP_MAX_COLS 22

/** Maximum rows renderable (limited by 512px hardware constraint) */
#define NG_TILEMAP_MAX_ROWS 32

/** @} */

/** @defgroup tilecoll Tile Collision Flags
 *  @brief Collision properties encoded in tile data.
 *  @{
 */

#define NG_TILE_SOLID    0x01 /**< Blocks movement (walls/floors) */
#define NG_TILE_PLATFORM 0x02 /**< One-way platform (solid from above) */
#define NG_TILE_SLOPE_L  0x04 /**< Left-to-right slope */
#define NG_TILE_SLOPE_R  0x08 /**< Right-to-left slope */
#define NG_TILE_HAZARD   0x10 /**< Damages player on contact */
#define NG_TILE_TRIGGER  0x20 /**< Triggers callback on contact */
#define NG_TILE_LADDER   0x40 /**< Climbable tile */

/** @} */

/** @defgroup tilecollres Collision Resolution Flags
 *  @brief Return values from NGTilemapResolveAABB().
 *  @{
 */

#define NG_COLL_NONE   0x00 /**< No collision */
#define NG_COLL_LEFT   0x01 /**< Hit tile on left */
#define NG_COLL_RIGHT  0x02 /**< Hit tile on right */
#define NG_COLL_TOP    0x04 /**< Hit tile above */
#define NG_COLL_BOTTOM 0x08 /**< Hit tile below (landed) */

/** @} */

/** @defgroup tilemaphandle Handle Type
 *  @{
 */

/** Tilemap handle type */
typedef s8 NGTilemapHandle;

/** @} */

/** @defgroup tilemapdata Tilemap Data Structures
 *  @brief Generated by progear_assets.py from Tiled TMX files.
 *  @{
 */

/**
 * Tilemap asset definition.
 * Generated by progear_assets.py from TMX files in assets.yaml.
 */
typedef struct {
    const char *name;          /**< Asset name */
    u16 width_tiles;           /**< Map width in tiles */
    u16 height_tiles;          /**< Map height in tiles */
    u16 base_tile;             /**< First tile in C-ROM for tileset */
    const u8 *tile_data;       /**< Tile indices (row-major, 1 byte per tile) */
    const u8 *collision_data;  /**< Collision flags (row-major, NULL = no collision) */
    const u8 *tile_to_palette; /**< Palette lookup table (256 entries) */
    u8 default_palette;        /**< Fallback palette for unmapped tiles */
} NGTilemapAsset;

/** @} */

/** @defgroup tilemaplife Lifecycle Functions
 *  @{
 */

/**
 * Create a tilemap from an asset.
 * @param asset Tilemap asset (generated by progear_assets.py)
 * @return Handle or NG_TILEMAP_INVALID if no slots available
 */
NGTilemapHandle NGTilemapCreate(const NGTilemapAsset *asset);

/**
 * Add tilemap to scene.
 * Position is in world coordinates (not viewport-relative).
 * @param tilemap Tilemap handle
 * @param world_x World X offset (fixed-point, top-left of tilemap)
 * @param world_y World Y offset (fixed-point)
 * @param z Z-index for render order
 */
void NGTilemapAddToScene(NGTilemapHandle tilemap, fixed world_x, fixed world_y, u8 z);

/**
 * Remove tilemap from scene (can re-add later).
 * @param tilemap Tilemap handle
 */
void NGTilemapRemoveFromScene(NGTilemapHandle tilemap);

/**
 * Destroy tilemap and free resources.
 * @param tilemap Tilemap handle
 */
void NGTilemapDestroy(NGTilemapHandle tilemap);

/** @} */

/** @defgroup tilemapprop Properties
 *  @{
 */

/**
 * Set tilemap world position.
 * @param tilemap Tilemap handle
 * @param world_x World X offset (fixed-point)
 * @param world_y World Y offset (fixed-point)
 */
void NGTilemapSetPos(NGTilemapHandle tilemap, fixed world_x, fixed world_y);

/**
 * Set tilemap Z-index.
 * @param tilemap Tilemap handle
 * @param z Z-index
 */
void NGTilemapSetZ(NGTilemapHandle tilemap, u8 z);

/**
 * Set tilemap visibility.
 * @param tilemap Tilemap handle
 * @param visible 1 to show, 0 to hide
 */
void NGTilemapSetVisible(NGTilemapHandle tilemap, u8 visible);

/**
 * Get tilemap world dimensions.
 * @param tilemap Tilemap handle
 * @param width_out Output: width in pixels (can be NULL)
 * @param height_out Output: height in pixels (can be NULL)
 */
void NGTilemapGetDimensions(NGTilemapHandle tilemap, u16 *width_out, u16 *height_out);

/** @} */

/** @defgroup tilemapcoll Collision Functions
 *  @{
 */

/**
 * Query tile collision at world position.
 * Fast O(1) lookup - no iteration.
 * @param tilemap Tilemap handle
 * @param world_x World X position (fixed-point)
 * @param world_y World Y position (fixed-point)
 * @return Collision flags, or 0 if out of bounds or no collision
 */
u8 NGTilemapGetCollision(NGTilemapHandle tilemap, fixed world_x, fixed world_y);

/**
 * Query tile index at grid position.
 * @param tilemap Tilemap handle
 * @param tile_x Tile X coordinate
 * @param tile_y Tile Y coordinate
 * @return Tile index, or 0 if out of bounds
 */
u8 NGTilemapGetTileAt(NGTilemapHandle tilemap, u16 tile_x, u16 tile_y);

/**
 * Test AABB collision against tilemap.
 * Checks all tiles overlapping the AABB.
 * @param tilemap Tilemap handle
 * @param x Center X (fixed-point)
 * @param y Center Y (fixed-point)
 * @param half_w Half-width (fixed-point)
 * @param half_h Half-height (fixed-point)
 * @param flags_out Output: OR'd collision flags of all overlapping tiles (can be NULL)
 * @return 1 if any solid collision, 0 if no collision
 */
u8 NGTilemapTestAABB(NGTilemapHandle tilemap, fixed x, fixed y, fixed half_w, fixed half_h,
                     u8 *flags_out);

/**
 * Resolve AABB collision against tilemap.
 * Pushes the AABB out of solid tiles using minimum displacement.
 * Handles one-way platforms (solid only when falling onto them).
 * @param tilemap Tilemap handle
 * @param x Center X (fixed-point, modified on collision)
 * @param y Center Y (fixed-point, modified on collision)
 * @param half_w Half-width (fixed-point)
 * @param half_h Half-height (fixed-point)
 * @param vel_x Velocity X (fixed-point, zeroed on horizontal collision)
 * @param vel_y Velocity Y (fixed-point, zeroed on vertical collision)
 * @return Collision direction bitmask (NG_COLL_LEFT|RIGHT|TOP|BOTTOM)
 */
u8 NGTilemapResolveAABB(NGTilemapHandle tilemap, fixed *x, fixed *y, fixed half_w, fixed half_h,
                        fixed *vel_x, fixed *vel_y);

/** @} */

/** @defgroup tilemapmod Tile Modification
 *  @{
 */

/**
 * Set tile at grid position (runtime modification).
 * Note: Requires RAM copy to be enabled for this tilemap.
 * @param tilemap Tilemap handle
 * @param tile_x Tile X coordinate
 * @param tile_y Tile Y coordinate
 * @param tile_index New tile index
 */
void NGTilemapSetTile(NGTilemapHandle tilemap, u16 tile_x, u16 tile_y, u8 tile_index);

/**
 * Set collision at grid position (runtime modification).
 * Note: Requires RAM copy to be enabled for this tilemap.
 * @param tilemap Tilemap handle
 * @param tile_x Tile X coordinate
 * @param tile_y Tile Y coordinate
 * @param collision New collision flags
 */
void NGTilemapSetCollision(NGTilemapHandle tilemap, u16 tile_x, u16 tile_y, u8 collision);

/** @} */

#endif /* _TILEMAP_H_ */
