/*
 * This file is part of ProGearSDK.
 * Copyright (c) 2024-2025 ProGearSDK contributors
 * SPDX-License-Identifier: MIT
 */

/**
 * @file ng_audio.h
 * @brief NeoGeo audio system - ADPCM-A (SFX) and ADPCM-B (Music) playback
 *
 * This module provides:
 * - Sound effect playback via ADPCM-A (6 channels, 18.5kHz, short samples)
 * - Music playback via ADPCM-B (1 channel, variable rate, long samples, looping)
 *
 * Audio Command Protocol (68k -> Z80):
 * - 0x10-0x1F: Play SFX 0-15 (center pan)
 * - 0x20-0x2F: Play music 0-15 (looping)
 * - 0x30: Stop music
 * - 0x40-0x4F: Play SFX 16-31 (center pan)
 * - 0x50-0x5F: Play music 16-31 (looping)
 * - 0x60-0x65: Stop SFX channel 0-5
 * - 0x66-0x6B: Set channel 0-5 volume (next byte = volume 0-31)
 * - 0x6C: Set music volume (next byte = volume 0-255)
 * - 0x70: Stop all audio
 * - 0x80-0x8F: Set master volume (0-15)
 * - 0xC0-0xCF: Play SFX 0-15 (left pan)
 * - 0xD0-0xDF: Play SFX 0-15 (right pan)
 * - 0xE0-0xEF: Play SFX 16-31 (left pan)
 * - 0xF0-0xFF: Play SFX 16-31 (right pan)
 */

#ifndef _NG_AUDIO_H_
#define _NG_AUDIO_H_

#include <ng_hardware.h>

/**
 * @defgroup audio Audio System
 * @ingroup hal
 * @brief ADPCM-A sound effects and ADPCM-B music playback.
 * @{
 */

/* Maximum number of sound effects and music tracks */
#define NG_AUDIO_MAX_SFX      32
#define NG_AUDIO_MAX_MUSIC    32
#define NG_AUDIO_MAX_CHANNELS 6 /* ADPCM-A channels for SFX */

/* Audio types for scene/actor binding */
typedef enum {
    NG_AUDIO_TYPE_SFX,   /* Sound effect (ADPCM-A) */
    NG_AUDIO_TYPE_MUSIC, /* Music/ambient (ADPCM-B) */
} NGAudioType;

/* Pan positions for stereo audio */
typedef enum {
    NG_PAN_LEFT = 0x80,   /* Left speaker only */
    NG_PAN_CENTER = 0xC0, /* Both speakers (center) */
    NG_PAN_RIGHT = 0x40,  /* Right speaker only */
} NGPan;

/**
 * Sound effect asset definition
 * Generated by progear_assets.py from audio assets in assets.yaml
 */
typedef struct {
    const char *name; /* Sound name for debugging */
    u8 index;         /* SFX index (0-31) */
} NGSfxAsset;

/**
 * Music asset definition
 * Generated by progear_assets.py from audio assets in assets.yaml
 */
typedef struct {
    const char *name; /* Music name for debugging */
    u8 index;         /* Music index (0-31) */
} NGMusicAsset;

/* ============================================================================
 * Initialization
 * ========================================================================== */

/**
 * Initialize the audio system
 * Call once at startup after BIOS init
 */
void NGAudioInit(void);

/* ============================================================================
 * Sound Effects (ADPCM-A)
 * ========================================================================== */

/**
 * Play a sound effect
 * Uses auto-channel assignment (first free channel)
 *
 * @param sfx_index Sound effect index (0-31)
 */
void NGSfxPlay(u8 sfx_index);

/**
 * Play a sound effect with specific pan
 *
 * @param sfx_index Sound effect index (0-31)
 * @param pan Pan position (NG_PAN_LEFT, NG_PAN_CENTER, NG_PAN_RIGHT)
 */
void NGSfxPlayPan(u8 sfx_index, NGPan pan);

/**
 * Play a sound effect from an asset
 *
 * @param sfx Pointer to sound effect asset
 */
static inline void NGSfxPlayAsset(const NGSfxAsset *sfx) {
    NGSfxPlay(sfx->index);
}

/**
 * Stop a specific SFX channel
 *
 * @param channel Channel to stop (0-5)
 */
void NGSfxStopChannel(u8 channel);

/**
 * Stop all sound effects
 */
void NGSfxStopAll(void);

/* ============================================================================
 * Music (ADPCM-B)
 * ========================================================================== */

/**
 * Play background music (looping)
 *
 * @param music_index Music index (0-31)
 */
void NGMusicPlay(u8 music_index);

/**
 * Play music from an asset
 *
 * @param music Pointer to music asset
 */
static inline void NGMusicPlayAsset(const NGMusicAsset *music) {
    NGMusicPlay(music->index);
}

/**
 * Stop music playback
 */
void NGMusicStop(void);

/**
 * Pause music playback (can be resumed)
 */
void NGMusicPause(void);

/**
 * Resume paused music
 */
void NGMusicResume(void);

/**
 * Check if music is currently playing
 *
 * @return 1 if playing, 0 if stopped
 */
u8 NGMusicIsPlaying(void);

/**
 * Check if music is paused
 *
 * @return 1 if paused, 0 if not
 */
u8 NGMusicIsPaused(void);

/* ============================================================================
 * Volume Control
 * ========================================================================== */

/**
 * Set master volume for all audio
 *
 * @param volume Volume level (0-15, 0=silent, 15=max)
 */
void NGAudioSetVolume(u8 volume);

/**
 * Set volume for a specific ADPCM-A channel
 * Allows per-channel volume control for SFX.
 *
 * @param channel Channel number (0-5)
 * @param volume Volume level (0-31, 0=silent, 31=max)
 */
void NGSfxSetChannelVolume(u8 channel, u8 volume);

/**
 * Set ADPCM-B (music) volume independently
 *
 * @param volume Volume level (0-255, 0=silent, 255=max)
 */
void NGMusicSetVolume(u8 volume);

/**
 * Stop all audio (SFX and music)
 */
void NGAudioStopAll(void);

/* ============================================================================
 * Low-Level Interface
 * ========================================================================== */

/**
 * Send a raw command to the Z80 audio driver
 * Waits for acknowledgment before returning
 *
 * @param cmd Command byte to send
 */
void NGAudioSendCommand(u8 cmd);

/**
 * Send a command without waiting for acknowledgment
 * Use with caution - may cause command loss if sent too fast
 *
 * @param cmd Command byte to send
 */
void NGAudioSendCommandAsync(u8 cmd);

/* ============================================================================
 * Audio State (for debugging/UI)
 * ========================================================================== */

/**
 * Get current music track index
 *
 * @return Current music index (0-31) or 0xFF if none playing
 */
u8 NGAudioGetCurrentMusic(void);

/**
 * Get current master volume
 *
 * @return Volume level (0-15)
 */
u8 NGAudioGetVolume(void);

/** @} */ /* end of audio group */

#endif /* _NG_AUDIO_H_ */
