/**
 * @file progear.h
 * @brief Convenience header that includes the entire ProGearSDK.
 *
 * Include this single header to access all SDK functionality:
 * @code
 * #include <progear.h>
 * @endcode
 *
 * Note: This does not include progear_assets.h, which is
 * application-specific and generated by the asset pipeline.
 */

/**
 * @defgroup sdk SDK - Game Engine
 * @brief High-level game engine built on the HAL.
 *
 * The SDK provides game-level abstractions for building NeoGeo games:
 * scenes, actors, cameras, terrain, physics, and more.
 *
 * Modules:
 * - @ref engine - Application lifecycle
 * - @ref scene - Scene/world management
 * - @ref actor - Game objects and sprites
 * - @ref camera - Viewport and tracking
 * - @ref terrain - Tile-based levels with collision
 * - @ref backdrop - Parallax backgrounds
 * - @ref visual - Visual asset definitions
 * - @ref graphic - Graphics abstraction API
 * - @ref physics - 2D physics simulation
 * - @ref lighting - Palette-based lighting effects
 * - @ref ui - Menu system
 * - @ref spring - Spring physics animations
 */

#ifndef NG_PROGEARSDK_H
#define NG_PROGEARSDK_H

/* Hardware Abstraction Layer (provides types, hardware, math, color,
 * palette, sprite, fix, input, audio, arena) */
#include <neogeo_hal.h>

/* Visual assets and graphics */
#include <visual.h>
#include <graphic.h>
#include <actor.h>
#include <scene.h>
#include <terrain.h>

/* Camera system */
#include <camera.h>

/* Backdrops (parallax background layers) */
#include <backdrop.h>

/* Physics */
#include <physics.h>

/* Lighting effects */
#include <lighting.h>

/* UI and animation */
#include <spring.h>
#include <ui.h>

/* Engine lifecycle */
#include <engine.h>

#endif /* NG_PROGEARSDK_H */
