/*
 * This file is part of ProGearSDK.
 * Copyright (c) 2024-2025 ProGearSDK contributors
 * SPDX-License-Identifier: MIT
 */

/**
 * @file scene.h
 * @brief Scene management.
 *
 * The NGScene is the "stage" where all visual objects exist.
 * It has a coordinate system with X, Y, and Z axes:
 * - X: 0 = leftmost, increases going right (no limit)
 * - Y: 0 = topmost, increases going down (max 512 due to hardware)
 * - Z: render order, 0 = back (rendered first), higher = front
 *
 * The scene owns a single **terrain** (tilemap) that actors interact with.
 * Use NGSceneSetTerrain() to set the terrain and NGSceneResolveCollision()
 * to handle actor collision with the terrain.
 *
 * @section sceneusage Usage
 * 1. Call NGSceneInit() at startup
 * 2. Set terrain with NGSceneSetTerrain()
 * 3. Create actors and backdrops, add them to scene
 * 4. Call NGSceneUpdate() and NGSceneDraw() each frame
 */

#ifndef NG_SCENE_H
#define NG_SCENE_H

#include <ng_types.h>
#include <ng_math.h>
#include <collision.h>
#include <terrain.h>

/* Forward declaration */
struct NGTerrainAsset;

/**
 * @defgroup scene Scene System
 * @ingroup sdk
 * @brief World/stage management with terrain and collision.
 * @{
 */

/** @name Constants */
/** @{ */

#define NG_SCENE_MAX_HEIGHT 512 /**< Maximum scene height in pixels */
#define NG_SCENE_VIEWPORT_W 320 /**< Viewport width (NeoGeo resolution) */
#define NG_SCENE_VIEWPORT_H 224 /**< Viewport height (NeoGeo resolution) */
/** @} */

/** @name Core Functions */
/** @{ */

/**
 * Initialize the scene system.
 * Call once at startup before creating any actors or parallax effects.
 */
void NGSceneInit(void);

/**
 * Update all scene objects.
 * Call once per frame. Updates animations and processes scene logic.
 */
void NGSceneUpdate(void);

/**
 * Draw all scene objects.
 * Call once per frame during VBlank. Renders objects in Z-order.
 */
void NGSceneDraw(void);

/**
 * Reset scene to empty state.
 * Destroys all actors and backdrops, clears hardware sprites.
 * Call when transitioning between levels/screens.
 */
void NGSceneReset(void);
/** @} */

/** @name Terrain */
/** @{ */

/**
 * Set the scene's terrain from a terrain asset.
 * The terrain is automatically added to the render queue.
 * @param asset Terrain asset (generated by progear_assets.py from tilemaps section)
 */
void NGSceneSetTerrain(const struct NGTerrainAsset *asset);

/**
 * Clear the scene's terrain.
 * Removes the terrain from rendering and collision.
 */
void NGSceneClearTerrain(void);

/**
 * Set terrain position in scene coordinates.
 * @param x X position (fixed-point)
 * @param y Y position (fixed-point)
 */
void NGSceneSetTerrainPos(fixed x, fixed y);

/**
 * Set terrain Z-index for render order.
 * @param z Z-index (0 = back, higher = front)
 */
void NGSceneSetTerrainZ(u8 z);

/**
 * Set terrain visibility.
 * @param visible 1 to show, 0 to hide
 */
void NGSceneSetTerrainVisible(u8 visible);

/**
 * Get terrain dimensions in pixels.
 * @param width Output: terrain width (can be NULL)
 * @param height Output: terrain height (can be NULL)
 */
void NGSceneGetTerrainBounds(u16 *width, u16 *height);

/**
 * Query collision flags at a world position.
 * @param x World X position (fixed-point)
 * @param y World Y position (fixed-point)
 * @return Collision flags, or 0 if no terrain or out of bounds
 */
u8 NGSceneGetCollisionAt(fixed x, fixed y);

/**
 * Test AABB collision against terrain.
 * @param x Center X (fixed-point)
 * @param y Center Y (fixed-point)
 * @param half_w Half-width (fixed-point)
 * @param half_h Half-height (fixed-point)
 * @param flags_out Output: OR'd collision flags (can be NULL)
 * @return 1 if solid collision, 0 if no collision
 */
u8 NGSceneTestCollision(fixed x, fixed y, fixed half_w, fixed half_h, u8 *flags_out);

/**
 * Resolve AABB collision against terrain.
 * Pushes the AABB out of solid tiles and handles one-way platforms.
 * @param x Center X (fixed-point, modified on collision)
 * @param y Center Y (fixed-point, modified on collision)
 * @param half_w Half-width (fixed-point)
 * @param half_h Half-height (fixed-point)
 * @param vel_x Velocity X (fixed-point, zeroed on horizontal collision)
 * @param vel_y Velocity Y (fixed-point, zeroed on vertical collision)
 * @return Collision direction bitmask (NG_COLL_LEFT|RIGHT|TOP|BOTTOM)
 */
u8 NGSceneResolveCollision(fixed *x, fixed *y, fixed half_w, fixed half_h, fixed *vel_x,
                           fixed *vel_y);

/**
 * Get tile index at grid position.
 * @param tile_x Tile X coordinate
 * @param tile_y Tile Y coordinate
 * @return Tile index, or 0 if no terrain or out of bounds
 */
u8 NGSceneGetTileAt(u16 tile_x, u16 tile_y);

/**
 * Set tile at grid position (runtime modification).
 * @param tile_x Tile X coordinate
 * @param tile_y Tile Y coordinate
 * @param tile_index New tile index
 */
void NGSceneSetTileAt(u16 tile_x, u16 tile_y, u8 tile_index);

/**
 * Set collision at grid position (runtime modification).
 * @param tile_x Tile X coordinate
 * @param tile_y Tile Y coordinate
 * @param collision New collision flags
 */
void NGSceneSetCollisionAt(u16 tile_x, u16 tile_y, u8 collision);

/**
 * Get the terrain handle for direct terrain API access.
 * Returns the handle set by NGSceneSetTerrain(), or NG_TERRAIN_INVALID
 * if no terrain is active. Use this to call NGTerrain*() functions directly,
 * which is equivalent to using the NGScene terrain proxy methods above.
 * @return Terrain handle, or NG_TERRAIN_INVALID
 */
NGTerrainHandle NGSceneGetTerrain(void);
/** @} */

/** @} */ /* end of scene group */

#endif /* NG_SCENE_H */
