/*
 * This file is part of ProGearSDK.
 * Copyright (c) 2024-2025 ProGearSDK contributors
 * SPDX-License-Identifier: MIT
 */

/**
 * @file visual.h
 * @brief Visual asset definitions.
 *
 * NGVisualAsset is a compile-time image asset defined in assets.yaml
 * and processed by the progear_assets.py tool. It can be static or animated.
 *
 * Visual assets are used to create NGActors and NGParallaxEffects.
 */

#ifndef NG_VISUAL_H
#define NG_VISUAL_H

#include <ng_types.h>

/**
 * @defgroup visual Visual Assets
 * @ingroup sdk
 * @brief Compiled image assets with optional animation.
 * @{
 */

/** @name Animation Definition */
/** @{ */

/**
 * Animation descriptor.
 * Defines a named animation sequence within a visual asset.
 */
typedef struct {
    const char *name; /**< Animation name (e.g., "idle", "walk") */
    u16 first_frame;  /**< First frame index */
    u16 frame_count;  /**< Number of frames */
    u8 speed;         /**< Ticks per frame (higher = slower) */
    u8 loop;          /**< 1 = loop, 0 = play once */
} NGAnimDef;
/** @} */

/** @name Collision Boxes */
/** @{ */

/**
 * Box kinds.
 *
 * These are deliberately about geometry rather than genre: a box says what
 * *region* it is, and the game decides what that means. A shmup typically uses
 * BODY and HURT, a racer BODY and TRIGGER, an action game all of them. Four
 * bits are left free for game-defined kinds.
 */
typedef enum {
    NG_BOX_BODY = 0x01,    /**< Physical extent: pushing, ground contact, footprint */
    NG_BOX_HURT = 0x02,    /**< Can be damaged here */
    NG_BOX_HIT = 0x04,     /**< Damages others while this frame is showing */
    NG_BOX_GUARD = 0x08,   /**< Intercepts incoming hits: blocks, parries, shields */
    NG_BOX_TRIGGER = 0x10, /**< Sensor: pickups, aggro range, checkpoints */
    NG_BOX_USER1 = 0x20,
    NG_BOX_USER2 = 0x40,
    NG_BOX_USER3 = 0x80
} NGBoxKind;

/**
 * A box in frame-local pixels, measured from the frame's top-left corner.
 *
 * Frame-local rather than anchor-relative on purpose: an actor's anchor can
 * change at runtime, and boxes must not move when it does. It also makes
 * mirroring exact - a horizontally flipped box is (frame_width - x - w).
 */
typedef struct {
    s16 x, y;
    u16 w, h;
    u8 kind;      /**< One NGBoxKind value */
    u8 _reserved; /**< Padding; keeps the struct 10 bytes and 2-byte aligned */
} NGBox;

/**
 * The boxes belonging to one animation frame.
 *
 * @c kinds is the union of every kind present in this frame, which lets a
 * query answer "is anything dangerous here?" with a single mask test instead
 * of walking the box list. Most frames of most animations have no active
 * hitbox, so this is the difference between scanning boxes every frame and
 * almost never touching them.
 */
typedef struct {
    u8 first_box; /**< Index into NGVisualAsset::boxes */
    u8 box_count; /**< Number of boxes for this frame */
    u8 kinds;     /**< Union of NGBoxKind values present */
    u8 _reserved; /**< Padding; keeps the struct 4 bytes */
} NGFrameBoxes;
/** @} */

/** @name Visual Asset Structure */
/** @{ */

/**
 * Visual asset definition.
 * Generated by progear_assets.py from source images in assets.yaml.
 * Max height is 512 pixels due to NeoGeo hardware limitations.
 */
typedef struct {
    const char *name;        /**< Asset name */
    u16 base_tile;           /**< First tile in C-ROM */
    u16 width_pixels;        /**< Natural width in pixels */
    u16 height_pixels;       /**< Natural height in pixels */
    u8 width_tiles;          /**< Width in 16x16 tiles */
    u8 height_tiles;         /**< Height in 16x16 tiles */
    const u16 *tilemap;      /**< Tile indices (row-major) */
    u8 palette;              /**< Default palette index */
    const u16 *palette_data; /**< Palette colors (16 entries), or NULL */

    /* Animation support (optional) */
    const NGAnimDef *anims; /**< Animation array (NULL if static) */
    u8 anim_count;          /**< Number of animations (0 if static) */
    u16 frame_count;        /**< Total frames (1 if static) */
    u16 tiles_per_frame;    /**< Tiles per animation frame */

    /* Collision boxes (optional) */
    const NGBox *boxes;              /**< Flat box array, or NULL if none */
    const NGFrameBoxes *frame_boxes; /**< One entry per frame, or NULL if none */
    u8 kinds;                        /**< Union of kinds across all frames */
} NGVisualAsset;
/** @} */

/** @name Tile Flags */
/** @{ */

#define NG_TILE_HFLIP 0x8000 /**< Horizontal flip flag */
#define NG_TILE_VFLIP 0x4000 /**< Vertical flip flag */
#define NG_TILE_MASK  0x0FFF /**< Tile index mask (bits 0-11) */
/** @} */

/** @} */ /* end of visual group */

#endif /* NG_VISUAL_H */
